import { useSelector } from "react-redux";
import "datatables.net-dt/css/jquery.dataTables.min.css";
import { COLUMNS_ADDRESS_DATA, COLUMNS_ADDRESS_TITLE, COLUMNS_AGE_DATA, COLUMNS_AGE_TITLE, COLUMNS_CITY_DATA, COLUMNS_CITY_TITLE, COLUMNS_COUNTRY_DATA, COLUMNS_COUNTRY_TITLE, COLUMNS_GOVT_ISSUED_ID_DATA, COLUMNS_GOVT_ISSUED_ID_TITLE, COLUMNS_GOVT_ISSUED_ID_TYPE_DATA, COLUMNS_GOVT_ISSUED_ID_TYPE_TITLE, COLUMNS_MOBILE_DATA, COLUMNS_MOBILE_TITLE, COLUMNS_NAME_DATA, COLUMNS_NAME_TITLE, COLUMNS_PIN_CODE_DATA, COLUMNS_PIN_CODE_TITLE, COLUMNS_SEX_DATA, COLUMNS_SEX_TITLE, COLUMNS_STATE_DATA, COLUMNS_STATE_TITLE } from '@Constants/index';
import { DataTable } from "./DataTable";

const columns = [
    { data: COLUMNS_NAME_DATA, title: COLUMNS_NAME_TITLE },
    { data: COLUMNS_AGE_DATA, title: COLUMNS_AGE_TITLE },
    { data: COLUMNS_SEX_DATA, title: COLUMNS_SEX_TITLE },
    { data: COLUMNS_MOBILE_DATA, title: COLUMNS_MOBILE_TITLE },
    { data: COLUMNS_GOVT_ISSUED_ID_TYPE_DATA, title: COLUMNS_GOVT_ISSUED_ID_TYPE_TITLE },
    { data: COLUMNS_GOVT_ISSUED_ID_DATA, title: COLUMNS_GOVT_ISSUED_ID_TITLE },
    { data: COLUMNS_ADDRESS_DATA, title: COLUMNS_ADDRESS_TITLE },
    { data: COLUMNS_STATE_DATA, title: COLUMNS_STATE_TITLE },
    { data: COLUMNS_CITY_DATA, title: COLUMNS_CITY_TITLE },
    { data: COLUMNS_COUNTRY_DATA, title: COLUMNS_COUNTRY_TITLE },
    { data: COLUMNS_PIN_CODE_DATA, title: COLUMNS_PIN_CODE_TITLE },
];

export function UserDetailsTable() {
    const userDetails = useSelector((state: InitialState) => state?.userDetails);
    return <DataTable data={userDetails} columns={columns} />;
};
